# Generated by Django 5.1.4 on 2025-01-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='answer',
            field=models.CharField(default='Default Answer', max_length=200),
        ),
    ]
